name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # you can test multiple versions if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build backend
        working-directory: ./backend
        run: npm run build --if-present

      # Optional: verify it can start (without keeping it running)
      - name: Check dev server startup
        working-directory: ./backend
        run: |
          nohup npm run dev &
          sleep 5
          pkill node
